import { Router } from 'express';
import { userRouter } from './user.routes';
import { permissionRouter } from './permission.routes';
import { roleRouter } from './role.routes';
import { rolePermissionRouter } from './rolePermission.routes';
import { userProfileRoutes } from './userProfile.routes';
import { areaRouter } from './area.routes';
import { fractionRouter } from './fraction.routes';
import { userAccessRouter } from './userAccess.routes';
import { categoryRouter } from './category.routes';
import { proposalRouter } from './proposal.routes';
import { authRouter } from './auth.routes';
import { proposalAssignmentRouter } from './proposalAssignment.routes';
import { proposalVoteRouter } from './proposalVote.routes';
import { proposalDiscussionRouter } from './proposalDiscussion.routes';
import { authentication } from '@/middlewares/authentication';

export const router = Router();
router.use('/auth', authRouter);
router.use(authentication);
router.use('/users', userRouter);
router.use('/permissions', permissionRouter);
router.use('/roles', roleRouter);
router.use('/rolePermissions', rolePermissionRouter);
router.use('/userProfiles', userProfileRoutes);
router.use('/areas', areaRouter);
router.use('/fractions', fractionRouter);
router.use('/userAccesses', userAccessRouter);
router.use('/categories', categoryRouter);
router.use('/proposals', proposalRouter);
router.use('/proposalAssignments', proposalAssignmentRouter);
router.use('/proposalVotes', proposalVoteRouter);
router.use('/proposalDiscussions', proposalDiscussionRouter);
