import { Router } from 'express';
import { userRouter } from './user.routes';
import { permissionRouter } from './permission.routes';
import { roleRouter } from './role.routes';
import { rolePermissionRouter } from './rolePermission.routes';
import { userProfileRoutes } from './userProfile.routes';
import { areaRouter } from './area.routes';
import { fractionRouter } from './fraction.routes';
import { userAccessRouter } from './userAccess.routes';
import { categoryRouter } from './category.routes';
import { proposalRouter } from './proposal.routes';
import { authRouter } from './auth.routes';
import { proposalAssignmentRouter } from './proposalAssignment.routes';
import { proposalVoteRouter } from './proposalVote.routes';
import { proposalDiscussionRouter } from './proposalDiscussion.routes';
import { proposalDiscussionVoteRouter } from './proposalDiscussionVote.routes';
import { proposalStatusRouter } from './proposalStatus.routes';
import { notificationRouter } from './notification.routes';
import { newsRouter } from './news.routes';
import { chatRouter } from './chat.routes';
import { publicRouter } from './public.routes';
import { commissionRouter } from './commission.routes';
import { positionRouter } from './position.routes';
import { dashboardRouter } from './dashboard.routes';
import { authentication } from '@/middlewares/authentication';

export const router = Router();
router.use('/auth', authRouter);
router.use('/public', publicRouter);
router.use(authentication);
router.use('/users', userRouter);
router.use('/permissions', permissionRouter);
router.use('/roles', roleRouter);
router.use('/rolePermissions', rolePermissionRouter);
router.use('/userProfiles', userProfileRoutes);
router.use('/areas', areaRouter);
router.use('/fractions', fractionRouter);
router.use('/userAccesses', userAccessRouter);
router.use('/categories', categoryRouter);
router.use('/proposals', proposalRouter);
router.use('/proposalAssignments', proposalAssignmentRouter);
router.use('/proposalVotes', proposalVoteRouter);
router.use('/proposalDiscussions', proposalDiscussionRouter);
router.use('/proposalDiscussionVotes', proposalDiscussionVoteRouter);
router.use('/proposalStatuses', proposalStatusRouter);
router.use('/notifications', notificationRouter);
router.use('/news', newsRouter);
router.use('/chats', chatRouter);
router.use('/commissions', commissionRouter);
router.use('/positions', positionRouter);
router.use('/dashboards', dashboardRouter);
